// Firebase configuration for Scenery Sync
// Generated by FlutterFire CLI - Project: scenery-sync-81273
// Do not edit manually. Re-run `flutterfire configure` to update.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ===== WEB PLATFORM =====

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_K-Ogus20Yc-3zd5H9FWZpbWpY-TSzU',
    appId: '1:521689710584:web:60efcdfa60c62854ffe00d',
    messagingSenderId: '521689710584',
    projectId: 'scenery-sync-81273',
    authDomain: 'scenery-sync-81273.firebaseapp.com',
    storageBucket: 'scenery-sync-81273.firebasestorage.app',
    measurementId: 'G-1LJMRMKS5K',
  );

  // ===== ANDROID PLATFORM =====

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAnXwhsELd3ThNyVVbKkpeSuE7TcDKoRE',
    appId: '1:521689710584:android:5ff81be155d4ad66ffe00d',
    messagingSenderId: '521689710584',
    projectId: 'scenery-sync-81273',
    storageBucket: 'scenery-sync-81273.firebasestorage.app',
  );

  // ===== iOS PLATFORM =====

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGwC_wkNxBFsCOJm7B8xUrD_9ZAp2PvE',
    appId: '1:521689710584:ios:c55785eca22c676fffe00d',
    messagingSenderId: '521689710584',
    projectId: 'scenery-sync-81273',
    storageBucket: 'scenery-sync-81273.firebasestorage.app',
    androidClientId: '521689710584-eies8sn9oc0aoilt0n2cevk08c8o45li.apps.googleusercontent.com',
    iosClientId: '521689710584-9qqlo545bgumu4sql2quv2hvcba5sb95.apps.googleusercontent.com',
    iosBundleId: 'com.example.scenerySync',
  );

  // ===== macOS PLATFORM =====

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDGwC_wkNxBFsCOJm7B8xUrD_9ZAp2PvE',
    appId: '1:521689710584:ios:c55785eca22c676fffe00d',
    messagingSenderId: '521689710584',
    projectId: 'scenery-sync-81273',
    storageBucket: 'scenery-sync-81273.firebasestorage.app',
    androidClientId: '521689710584-eies8sn9oc0aoilt0n2cevk08c8o45li.apps.googleusercontent.com',
    iosClientId: '521689710584-9qqlo545bgumu4sql2quv2hvcba5sb95.apps.googleusercontent.com',
    iosBundleId: 'com.example.scenerySync',
  );

  // ===== WINDOWS PLATFORM =====

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL_K-Ogus20Yc-3zd5H9FWZpbWpY-TSzU',
    appId: '1:521689710584:web:34308ae16dd8bd9affe00d',
    messagingSenderId: '521689710584',
    projectId: 'scenery-sync-81273',
    authDomain: 'scenery-sync-81273.firebaseapp.com',
    storageBucket: 'scenery-sync-81273.firebasestorage.app',
    measurementId: 'G-4NGZ3WSPF6',
  );

}